"""Context Engine 输入装配公共门面（2026-09-06 审查批次三拆分）。

历史上本文件是 3600+ 行的单一实现；现已按职责拆分为：

- ``builders_common``  共享 helper（领域 excerpt / 注入策略 / peek / 指纹）
- ``relevance``        相关性裁剪
- ``cache``            装配缓存与指纹
- ``canon``            ReferenceCanon 注入
- ``director_input``   build_director_input
- ``writer_input``     build_writer_input / paged
- ``observer_input``   build_observer_input

本文件保留**全部既有顶层名的再导出**（显式 import + ``__all__``），
任何 ``from packages.core.context_engine.builders import X``（含私有名）
与 ``builders.X`` 属性访问行为不变；新代码请直接从子模块导入。
"""

from __future__ import annotations

from .builders_common import (
    _AUTHOR_STYLE_SAMPLES_INSTRUCTION,
    _DEBT_OPEN_STATUSES,
    _DEFAULT_STYLE_CONSTRAINTS,
    _DEFAULT_TARGET_WORD_COUNT,
    _FORESHADOW_OVERDUE_CHAPTERS,
    _HOOK_OPEN_STATUSES,
    _INJECT_MODES,
    _MIN_ALIAS_LEN,
    _OPEN_HOOKS_CAP,
    _PLANTED_HOOK_STATUSES,
    _RECENT_SUMMARY_CAP,
    _RECENT_SUMMARY_PER_CHARS,
    _STYLE_SAMPLE_PER_CHARS,
    _STYLE_SAMPLES_CAP,
    _SUMMARY_LINE_MAX_CHARS,
    _apply_injection_policy,
    _author_style_samples,
    _build_trigger_corpus,
    _chapter_project_id,
    _character_state_excerpts,
    _collect_touched_entity_ids,
    _director_plan_summary,
    _extract_sensory_anchors,
    _fingerprint_word_band_json,
    _hook_ledger_excerpt,
    _inject_scene_word_budget,
    _is_triggered,
    _latest_draft,
    _load_aliases,
    _load_inject_mode,
    _narrative_debt_excerpt,
    _open_foreshadow_list,
    _parse_json,
    _peek_active_canon_id,
    _peek_chapter_no_state_version,
    _peek_chapter_no_state_version_plan,
    _peek_project_id_from_chapter,
    _peek_project_word_band_json,
    _plot_graph_excerpt,
    _previous_chapter_tail,
    _project_overdue_chapters,
    _recent_chapter_summaries,
    _recent_prose_tail,
    _row_to_chapter,
    _row_to_project,
    _safe_copy,
    _summarize_entity,
    _truncate_summaries_to_token_budget,
    _world_state_excerpts,
)
from .cache import (
    _CACHE_MAX_SIZE,
    _FINGERPRINT_LEN,
    _FINGERPRINT_NONE,
    _FINGERPRINT_UNCACHED,
    _assembly_cache,
    _cache_get,
    _cache_lock,
    _cache_put,
    _cache_reset,
    _fingerprint_plan_json,
    _fingerprint_scene_plan,
    _invalidate_cache_for_chapter,
)
from .canon import (
    _REFERENCE_CANON_CONSUMER_DIRECTOR,
    _REFERENCE_CANON_CONSUMER_PLANNER,
    _REFERENCE_CANON_CONSUMER_WRITER,
    _REFERENCE_CANON_EMOTION_CAP,
    _REFERENCE_CANON_PAYOFF_CAP,
    _REFERENCE_CANON_PROTAGONIST_FOILS_CAP,
    _REFERENCE_CANON_PROTAGONIST_TAGS_CAP,
    _REFERENCE_CANON_SPINE_CAP,
    _REFERENCE_CANON_STYLE_MAX_CHARS,
    _reference_canon_excerpt,
    _select_emotion_window,
    _trim_style_params,
)
from .director_input import (
    _build_director_input_uncached,
    _build_plan_corpus,
    _extract_plan_entity_names,
    _recall_passages,
    build_director_input,
)
from .observer_input import (
    _DEFAULT_EVENTS_WINDOW_CHAPTERS,
    _DEFAULT_RECENT_EVENT_IDS_LIMIT,
    _compact_event,
    _compact_open_debt,
    _compact_open_hook,
    _load_event_chapter_no_map,
    _load_recent_event_ids,
    _summarize_character,
    _summarize_debt,
    _summarize_faction,
    _summarize_hook,
    _summarize_location,
    _summarize_relationship,
    _summarize_world_rule,
    _trim_snapshot_for_observer,
    build_observer_input,
)
from .relevance import (
    _apply_relevance_trim,
    _extract_involved_entities,
    _is_character_relevant,
    _is_faction_relevant,
    _is_location_relevant,
    _resolve_relevance_trim,
    _summarize_entity_for_relevance,
)
from .writer_input import (
    _SUMMARY_KEYS_CHARACTER,
    _SUMMARY_KEYS_FACTION,
    _SUMMARY_KEYS_HOOK,
    _SUMMARY_KEYS_LOCATION,
    _WRITER_KEEP_RECENT_COMMITS,
    _WRITER_RESOLVED_HOOKS_KEEP,
    _audience_blocks_writer,
    _build_writer_input_paged,
    _build_writer_input_uncached,
    _filter_hidden_by_reveal_policies,
    _summarize_character_for_writer,
    _summarize_faction_for_writer,
    _summarize_hook_for_writer,
    _summarize_location_for_writer,
    build_writer_input,
)

__all__ = [
    "_AUTHOR_STYLE_SAMPLES_INSTRUCTION",
    "_CACHE_MAX_SIZE",
    "_DEBT_OPEN_STATUSES",
    "_DEFAULT_EVENTS_WINDOW_CHAPTERS",
    "_DEFAULT_RECENT_EVENT_IDS_LIMIT",
    "_DEFAULT_STYLE_CONSTRAINTS",
    "_DEFAULT_TARGET_WORD_COUNT",
    "_FINGERPRINT_LEN",
    "_FINGERPRINT_NONE",
    "_FINGERPRINT_UNCACHED",
    "_FORESHADOW_OVERDUE_CHAPTERS",
    "_HOOK_OPEN_STATUSES",
    "_INJECT_MODES",
    "_MIN_ALIAS_LEN",
    "_OPEN_HOOKS_CAP",
    "_PLANTED_HOOK_STATUSES",
    "_RECENT_SUMMARY_CAP",
    "_RECENT_SUMMARY_PER_CHARS",
    "_REFERENCE_CANON_CONSUMER_DIRECTOR",
    "_REFERENCE_CANON_CONSUMER_PLANNER",
    "_REFERENCE_CANON_CONSUMER_WRITER",
    "_REFERENCE_CANON_EMOTION_CAP",
    "_REFERENCE_CANON_PAYOFF_CAP",
    "_REFERENCE_CANON_PROTAGONIST_FOILS_CAP",
    "_REFERENCE_CANON_PROTAGONIST_TAGS_CAP",
    "_REFERENCE_CANON_SPINE_CAP",
    "_REFERENCE_CANON_STYLE_MAX_CHARS",
    "_STYLE_SAMPLES_CAP",
    "_STYLE_SAMPLE_PER_CHARS",
    "_SUMMARY_KEYS_CHARACTER",
    "_SUMMARY_KEYS_FACTION",
    "_SUMMARY_KEYS_HOOK",
    "_SUMMARY_KEYS_LOCATION",
    "_SUMMARY_LINE_MAX_CHARS",
    "_WRITER_KEEP_RECENT_COMMITS",
    "_WRITER_RESOLVED_HOOKS_KEEP",
    "_apply_injection_policy",
    "_apply_relevance_trim",
    "_assembly_cache",
    "_audience_blocks_writer",
    "_author_style_samples",
    "_build_director_input_uncached",
    "_build_plan_corpus",
    "_build_trigger_corpus",
    "_build_writer_input_paged",
    "_build_writer_input_uncached",
    "_cache_get",
    "_cache_lock",
    "_cache_put",
    "_cache_reset",
    "_chapter_project_id",
    "_character_state_excerpts",
    "_collect_touched_entity_ids",
    "_compact_event",
    "_compact_open_debt",
    "_compact_open_hook",
    "_director_plan_summary",
    "_extract_involved_entities",
    "_extract_plan_entity_names",
    "_extract_sensory_anchors",
    "_filter_hidden_by_reveal_policies",
    "_fingerprint_plan_json",
    "_fingerprint_scene_plan",
    "_fingerprint_word_band_json",
    "_hook_ledger_excerpt",
    "_inject_scene_word_budget",
    "_invalidate_cache_for_chapter",
    "_is_character_relevant",
    "_is_faction_relevant",
    "_is_location_relevant",
    "_is_triggered",
    "_latest_draft",
    "_load_aliases",
    "_load_event_chapter_no_map",
    "_load_inject_mode",
    "_load_recent_event_ids",
    "_narrative_debt_excerpt",
    "_open_foreshadow_list",
    "_parse_json",
    "_peek_active_canon_id",
    "_peek_chapter_no_state_version",
    "_peek_chapter_no_state_version_plan",
    "_peek_project_id_from_chapter",
    "_peek_project_word_band_json",
    "_plot_graph_excerpt",
    "_previous_chapter_tail",
    "_project_overdue_chapters",
    "_recall_passages",
    "_recent_chapter_summaries",
    "_recent_prose_tail",
    "_reference_canon_excerpt",
    "_resolve_relevance_trim",
    "_row_to_chapter",
    "_row_to_project",
    "_safe_copy",
    "_select_emotion_window",
    "_summarize_character",
    "_summarize_character_for_writer",
    "_summarize_debt",
    "_summarize_entity",
    "_summarize_entity_for_relevance",
    "_summarize_faction",
    "_summarize_faction_for_writer",
    "_summarize_hook",
    "_summarize_hook_for_writer",
    "_summarize_location",
    "_summarize_location_for_writer",
    "_summarize_relationship",
    "_summarize_world_rule",
    "_trim_snapshot_for_observer",
    "_trim_style_params",
    "_truncate_summaries_to_token_budget",
    "_world_state_excerpts",
    "build_director_input",
    "build_observer_input",
    "build_writer_input",
]
